apiVersion: v1
kind: Namespace
metadata:
  name: eventxperience

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: eventxperience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: appdb
            - name: MYSQL_USER
              value: appuser
            - name: MYSQL_PASSWORD
              value: apppass
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: eventxperience
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: eventxperience
spec:
  selector:
    app: mysql
  ports:
    - port: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: eventxperience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: eventxperience
spec:
  selector:
    app: redis
  ports:
    - port: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: eventxperience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: appuser
            - name: RABBITMQ_DEFAULT_PASS
              value: apppass
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: eventxperience
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
    - name: management
      port: 15672

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: eventxperience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: myapp-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8090"
            - name: DB_CONNECTION_STRING
              value: "Server=mysql;Port=3306;Database=appdb;User=appuser;Password=apppass"
            - name: REDIS_CONNECTION
              value: "redis:6379"
            - name: RABBIT_CONNECTION
              value: "amqp://appuser:apppass@rabbitmq:5672"
            - name: JWT_SECRET_KEY
              value: "amazing_secret_key_yup_yes_abcdef123"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: eventxperience
spec:
  selector:
    app: backend
  ports:
    - port: 8090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: eventxperience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: myapp-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBIT_CONNECTION
              value: "amqp://appuser:apppass@rabbitmq:5672"
            - name: REDIS_CONNECTION
              value: "redis:6379"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: eventxperience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: myapp-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3090
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: eventxperience
spec:
  selector:
    app: frontend
  ports:
    - port: 3090
  type: NodePort
