apiVersion: v1
kind: Namespace
metadata:
  name: eventxperience
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: eventxperience
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: appdb
            - name: MYSQL_USER
              value: appuser
            - name: MYSQL_PASSWORD
              value: apppass
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: eventxperience
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: eventxperience
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: eventxperience
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: eventxperience
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: eventxperience
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: eventxperience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: eventxperience-backend:latest
          ports:
            - containerPort: 8090
          env:
            - name: DB_CONNECTION_STRING
              value: "Server=mysql;Port=3306;Database=appdb;User=root;Password=root"

            - name: REDIS_CONNECTION
              value: "redis:6379"

            - name: MONGO_CONNECTION
              value: "mongodb://mongo:27017/eventxperience"

            - name: JWT_SECRET_KEY
              value: "amazing_secret_key_yup_yes_abcdef123"
            - name: JWT_SECRET_KEY_REFRESH
              value: "amazing_secret_key_yup_yes_abcdef123"
            - name: JWT_SECRET_KEY_VERIFY
              value: "amazing_secret_key_yup_yes_abcdef123"
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: eventxperience
spec:
  selector:
    app: backend
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: eventxperience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: eventxperience-frontend:latest
          ports:
            - containerPort: 3090
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: eventxperience
spec:
  selector:
    app: frontend
  ports:
    - port: 3090
      targetPort: 3090
  type: NodePort
